### PR TITLE
Build for Linux RISC-V 64

### PR DESCRIPTION
**Pull request by Glavo**

### CODE REVIEW

**Comment by Spasi** [comment]
Hey @Glavo,

If the riscv64 build requires Ubuntu 20.04, it would be better to extract it to a separate job (or maybe use a matrix variable?) and keep arm32/arm64 on 18.04. This is important for GLIBC compatibility.

**Comment by Glavo** [comment]
> Hey @Glavo,
> 
> If the riscv64 build requires Ubuntu 20.04, it would be better to extract it to a separate job (or maybe use a matrix variable?) and keep arm32/arm64 on 18.04. This is important for GLIBC compatibility.

Okay.

When can we give up on Ubuntu 18.04? The general support for it is about to end the day after tomorrow. Do we still need to continue compatibility with it after that?

**Comment by Glavo** [comment]
@Spasi I have updated this PR and now only use ubuntu 20.04 for building RISC-V 64 library.

**Comment by Spasi** [comment]
> When can we give up on Ubuntu 18.04? The general support for it is about to end the day after tomorrow. Do we still need to continue compatibility with it after that?

It's not about Ubuntu, it's the GLIBC version that comes with 18.04. The problem on Linux is that any binaries you build will depend on the GLIBC version present on the build host.

Ideally, you'd want to build with a modern GCC running on a host with an old GLIBC, for as wide compatibility as possible. The best solution I've found so far is a CentOS 7 image (GLIBC 2.17) with `centos-release-scl` and `devtoolset-11-gcc-c++` (GCC 11). You can see how that works in the x64 job. Unfortunately, nothing as elegant exists for cross-compilation (that I know of). We could use a VM (e.g. QEMU), but they are notoriously slow and problematic.

**Comment by Spasi** [comment]
Thanks @Glavo, merged manually.

**Comment by Spasi** [comment]
@Glavo I've merged the cross jobs again, but used a matrix variable (`CONTAINER`) to differentiate the ARM & RISC-V paths. Other than the Ubuntu version, the main difference between the two is the "Upgrade git" step, where I used an `if` expression to run the appropriate step for each path.

It's less verbose this way, you may want to use it as reference for the other dependencies.

**Pull request closed without merging**
